use mydb;

CREATE TABLE product (
id INT(8) UNSIGNED AUTO_INCREMENT PRIMARY KEY,
name VARCHAR(50) NOT NULL,
brand VARCHAR(50) NOT NULL,
colour VARCHAR(50) NOT NULL,
price VARCHAR(50) NOT NULL,
images VARCHAR(50) NOT NULL,
sizes VARCHAR(50) NOT NULL,
special BOOLEAN NOT NULL,
specialprice VARCHAR(50),
specialdescription VARCHAR(255),
category VARCHAR(255),
length VARCHAR(255),
width VARCHAR(255),
reg_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
)
